import { Actor, ActorTier, Genre, Script, RivalStudio } from "./types";

export const INITIAL_BALANCE = 5000000;
export const START_YEAR = 2003;
export const START_MONTH = 1;

export const GENRES = Object.values(Genre);

const STUDIO_NAMES = [
  "Metro-G-M",
  "Global-Universal",
  "IndieCloud Pictures",
  "Paramount-ish",
  "Warner-Brothers-ish",
  "Sony-ish Entertainment",
  "Disney-ish Films",
  "Miramax-alike",
  "New Line-alike",
  "Lionsgate-ish",
  "Summit-alike",
  "Fox-ish Searchlight",
  "Focus-ish Features",
  "A24-proto",
  "Dimension-alike",
  "DreamWorks-ish",
  "Pixar-ish Animation",
  "Castle Rock-ish",
  "Orion-ish",
  "Touchstone-ish",
  "New Line-ish",
  "PolyGram-ish",
  "MGM-ish",
  "Screen Gems-ish",
  "Tristar-ish",
  "Hollywood-ish Pictures",
  "Working Title-ish",
  "Imagine-ish",
  "Amblin-ish",
  "Village-Roadshow-ish",
];

const PERSONALITIES: RivalStudio["personality"][] = [
  "Aggressive",
  "Friendly",
  "Elitist",
  "Chaotic",
];

export const RIVAL_STUDIOS: RivalStudio[] = STUDIO_NAMES.map((name, i) => ({
  id: `r${i}`,
  name,
  reputation: 30 + Math.floor(Math.random() * 60),
  balance: 5000000 + Math.floor(Math.random() * 95000000),
  yearlyRevenue: 0,
  color: `hsl(${i * 12}, 70%, 40%)`,
  personality: PERSONALITIES[Math.floor(Math.random() * PERSONALITIES.length)],
  relationship: 0,
  ownedActors: [],
  ownedScripts: [],
  activeProjects: [],
}));

export const SEED_ACTORS: Actor[] = [
  // ========== A-LIST (6 actors) ==========
  {
    id: "a1",
    name: "Marcus Sterling",
    age: 42,
    gender: "Male",
    tier: ActorTier.AList,
    salary: 2500000,
    reputation: 98,
    skill: 92,
    genres: [Genre.Action, Genre.Drama],
    img: "",
    status: "Available",
    bio: "Three-time Academy nominee known for intense method acting. Once lived in a monastery for 6 months to prepare for a role. Refuses to do press junkets.",
    visualDescription: "Salt-and-pepper hair, intense blue eyes, always wears black.",
    personality: ["Method Actor", "Reclusive", "Perfectionist"],
    relationships: { a3: 30, a7: -20 },
  },
  {
    id: "a2",
    name: "Vivienne Cross",
    age: 34,
    gender: "Female",
    tier: ActorTier.AList,
    salary: 2200000,
    reputation: 96,
    skill: 90,
    genres: [Genre.Romance, Genre.Drama, Genre.Comedy],
    img: "",
    status: "Available",
    bio: "America's sweetheart turned serious actress. Started in teen comedies, now dominates awards season. Known for her infectious laugh and fierce contract negotiations.",
    visualDescription: "Radiant smile, auburn hair, designer everything.",
    personality: ["Charismatic", "Business-Savvy", "Demanding"],
    relationships: { a5: 45, a8: 20 },
  },
  {
    id: "a3",
    name: "Damien Locke",
    age: 38,
    gender: "Male",
    tier: ActorTier.AList,
    salary: 2100000,
    reputation: 94,
    skill: 88,
    genres: [Genre.SciFi, Genre.Action, Genre.Thriller],
    img: "",
    status: "Available",
    bio: "Former stuntman turned leading man. Does all his own stunts and has broken 23 bones on set. Extremely superstitious—won't start filming on Tuesdays.",
    visualDescription: "Rugged features, visible scars, athletic build.",
    personality: ["Daredevil", "Superstitious", "Loyal"],
    relationships: { a1: 30, a6: 15 },
  },
  {
    id: "a4",
    name: "Celeste Monroe",
    age: 29,
    gender: "Female",
    tier: ActorTier.AList,
    salary: 1900000,
    reputation: 95,
    skill: 86,
    genres: [Genre.Action, Genre.Thriller, Genre.SciFi],
    img: "",
    status: "Available",
    bio: "The reigning action queen. Trained in three martial arts and speaks five languages. Tabloids love her mysterious personal life and rumored feuds.",
    visualDescription: "Striking features, always camera-ready, athletic.",
    personality: ["Fierce", "Private", "Competitive"],
    relationships: { a2: -15, a9: 25 },
  },
  {
    id: "a5",
    name: "Harrison Blake",
    age: 55,
    gender: "Male",
    tier: ActorTier.AList,
    salary: 2800000,
    reputation: 99,
    skill: 94,
    genres: [Genre.Action, Genre.Drama, Genre.SciFi],
    img: "",
    status: "Available",
    bio: "Living legend. Four decades of iconic roles. Known for improvising his best lines. Once punched a director and somehow became more famous.",
    visualDescription: "Weathered charm, graying temples, sardonic grin.",
    personality: ["Legendary", "Unpredictable", "Gruff"],
    relationships: { a2: 45, a1: 10 },
  },
  {
    id: "a6",
    name: "Natasha Vance",
    age: 31,
    gender: "Female",
    tier: ActorTier.AList,
    salary: 2000000,
    reputation: 93,
    skill: 91,
    genres: [Genre.Drama, Genre.Romance, Genre.Thriller],
    img: "",
    status: "Available",
    bio: "Stage actress who conquered Hollywood. Tony winner at 24, Oscar winner at 28. Known for transformative performances and absolutely zero tolerance for mediocrity.",
    visualDescription: "Elegant, expressive eyes, theatrical presence.",
    personality: ["Theatrical", "Demanding", "Brilliant"],
    relationships: { a3: 15, a12: 35 },
  },

  // ========== B-LIST (8 actors) ==========
  {
    id: "a7",
    name: "Derek Chambers",
    age: 45,
    gender: "Male",
    tier: ActorTier.BList,
    salary: 800000,
    reputation: 75,
    skill: 82,
    genres: [Genre.Action, Genre.Comedy],
    img: "",
    status: "Available",
    bio: "Former action star trying to transition to comedy. Had a messy divorce that tanked his reputation. Currently on a redemption arc the tabloids love to cover.",
    visualDescription: "Still fit, dad jokes energy, trying too hard.",
    personality: ["Insecure", "Desperate", "Actually Funny"],
    relationships: { a1: -20, a15: 30 },
  },
  {
    id: "a8",
    name: "Miranda Chen",
    age: 36,
    gender: "Female",
    tier: ActorTier.BList,
    salary: 750000,
    reputation: 78,
    skill: 85,
    genres: [Genre.Drama, Genre.Thriller, Genre.Horror],
    img: "",
    status: "Available",
    bio: "Critically acclaimed but never quite breaks through to the A-list. Industry insiders say she's 'one role away' from superstardom. Has been 'one role away' for five years.",
    visualDescription: "Understated elegance, always looks thoughtful.",
    personality: ["Underrated", "Patient", "Quietly Ambitious"],
    relationships: { a2: 20, a6: 25 },
  },
  {
    id: "a9",
    name: "Tyler Finn",
    age: 27,
    gender: "Male",
    tier: ActorTier.BList,
    salary: 650000,
    reputation: 80,
    skill: 72,
    genres: [Genre.Romance, Genre.Comedy, Genre.Drama],
    img: "",
    status: "Available",
    bio: "Teen heartthrob aging out of his niche. Trying to be taken seriously but keeps getting cast as 'the boyfriend.' Has a problematic stan culture following him around.",
    visualDescription: "Pretty boy looks, perfect hair, puppy dog eyes.",
    personality: ["Charming", "Naive", "People Pleaser"],
    relationships: { a4: 25, a11: -10 },
  },
  {
    id: "a10",
    name: "Josephine Hart",
    age: 48,
    gender: "Female",
    tier: ActorTier.BList,
    salary: 700000,
    reputation: 82,
    skill: 89,
    genres: [Genre.Drama, Genre.Thriller],
    img: "",
    status: "Available",
    bio: "Character actress who steals every scene. Oscar-nominated for supporting roles three times. Directors fight to get her for 'the mom who reveals a dark secret.'",
    visualDescription: "Distinguished, maternal warmth hiding steel.",
    personality: ["Scene-Stealer", "Generous", "Wise"],
    relationships: { a5: 20, a6: 30 },
  },
  {
    id: "a11",
    name: "Ricky Delgado",
    age: 33,
    gender: "Male",
    tier: ActorTier.BList,
    salary: 600000,
    reputation: 73,
    skill: 78,
    genres: [Genre.Comedy, Genre.Action, Genre.Romance],
    img: "",
    status: "Available",
    bio: "SNL alumnus who made the jump to films. Known for explosive energy and absolutely chaotic talk show appearances. May or may not have a gambling problem.",
    visualDescription: "Animated expressions, wild energy, always moving.",
    personality: ["Manic", "Hilarious", "Self-Destructive"],
    relationships: { a9: -10, a15: 40 },
  },
  {
    id: "a12",
    name: "Elizabeth Frost",
    age: 40,
    gender: "Female",
    tier: ActorTier.BList,
    salary: 850000,
    reputation: 84,
    skill: 87,
    genres: [Genre.Horror, Genre.Thriller, Genre.Drama],
    img: "",
    status: "Available",
    bio: "Scream queen who's evolved into a genre icon. Producers know if she's in a horror film, it's quality. Runs a popular horror podcast in her spare time.",
    visualDescription: "Striking, can go from girl-next-door to terrifying.",
    personality: ["Genre-Savvy", "Professional", "Secretly Nerdy"],
    relationships: { a6: 35, a8: 20 },
  },
  {
    id: "a13",
    name: "Vincent Cole",
    age: 52,
    gender: "Male",
    tier: ActorTier.BList,
    salary: 700000,
    reputation: 76,
    skill: 84,
    genres: [Genre.Drama, Genre.Thriller, Genre.SciFi],
    img: "",
    status: "Available",
    bio: "Once A-list in the 80s, now a reliable character actor. Has made peace with his faded fame and genuinely enjoys the work. Kids don't know him but their parents do.",
    visualDescription: "Distinguished, silver fox, carries gravitas.",
    personality: ["Humble", "Professional", "Nostalgic"],
    relationships: { a5: 15, a1: 5 },
  },
  {
    id: "a14",
    name: "Simone Baptiste",
    age: 28,
    gender: "Female",
    tier: ActorTier.BList,
    salary: 550000,
    reputation: 77,
    skill: 80,
    genres: [Genre.Romance, Genre.Drama, Genre.Comedy],
    img: "",
    status: "Available",
    bio: "Rising star from indie darling to mainstream recognition. Critics adore her, audiences are catching on. Known for choosing interesting projects over paychecks.",
    visualDescription: "Natural beauty, expressive, effortlessly cool.",
    personality: ["Artistic", "Selective", "Authentic"],
    relationships: { a2: 15, a19: 25 },
  },

  // ========== C-LIST (10 actors) ==========
  {
    id: "a15",
    name: "Chuck Martinez",
    age: 44,
    gender: "Male",
    tier: ActorTier.CList,
    salary: 250000,
    reputation: 55,
    skill: 70,
    genres: [Genre.Action, Genre.Comedy],
    img: "",
    status: "Available",
    bio: "The guy you recognize but can't name. Been in 47 movies, usually as 'Cop #2' or 'Guy in Bar.' Somehow has a cult following for his cameos.",
    visualDescription: "Generic leading man look, forgettable but likeable.",
    personality: ["Everyman", "Hardworking", "Self-Aware"],
    relationships: { a7: 30, a11: 40 },
  },
  {
    id: "a16",
    name: "Tiffany Marlowe",
    age: 26,
    gender: "Female",
    tier: ActorTier.CList,
    salary: 200000,
    reputation: 60,
    skill: 65,
    genres: [Genre.Horror, Genre.Romance],
    img: "",
    status: "Available",
    bio: "Former model trying to break into acting. More famous for who she's dated than her roles. Actually more talented than people give her credit for.",
    visualDescription: "Model gorgeous, knows her angles, underestimated.",
    personality: ["Underestimated", "Ambitious", "Resilient"],
    relationships: { a9: 20, a4: -25 },
  },
  {
    id: "a17",
    name: "Bernard 'Bernie' Walsh",
    age: 58,
    gender: "Male",
    tier: ActorTier.CList,
    salary: 180000,
    reputation: 52,
    skill: 75,
    genres: [Genre.Drama, Genre.Comedy],
    img: "",
    status: "Available",
    bio: "Theater veteran who never made it big in Hollywood. Does one film a year to pay for his passion projects. Students study his stage work.",
    visualDescription: "Shakespearean bearing, voice like velvet.",
    personality: ["Theatrical", "Bitter", "Talented"],
    relationships: { a6: 10, a13: 25 },
  },
  {
    id: "a18",
    name: "Crystal Powers",
    age: 31,
    gender: "Female",
    tier: ActorTier.CList,
    salary: 220000,
    reputation: 58,
    skill: 62,
    genres: [Genre.Action, Genre.SciFi],
    img: "",
    status: "Available",
    bio: "Former fitness influencer turned actress. Takes every action role she can get. Actually does train harder than most stunt doubles.",
    visualDescription: "Incredibly fit, Instagram-ready, determined.",
    personality: ["Disciplined", "Social Media Obsessed", "Driven"],
    relationships: { a4: 15, a16: -10 },
  },
  {
    id: "a19",
    name: "Omar Hassan",
    age: 35,
    gender: "Male",
    tier: ActorTier.CList,
    salary: 230000,
    reputation: 63,
    skill: 78,
    genres: [Genre.Drama, Genre.Thriller],
    img: "",
    status: "Available",
    bio: "British-trained actor struggling in Hollywood. Gets typecast constantly but delivers powerful performances anyway. One good role away from breaking out.",
    visualDescription: "Intense gaze, commanding presence, frustrated.",
    personality: ["Frustrated", "Talented", "Determined"],
    relationships: { a14: 25, a1: 5 },
  },
  {
    id: "a20",
    name: "Penny Nguyen",
    age: 24,
    gender: "Female",
    tier: ActorTier.CList,
    salary: 175000,
    reputation: 50,
    skill: 68,
    genres: [Genre.Comedy, Genre.Romance],
    img: "",
    status: "Available",
    bio: "YouTube comedian who got a movie deal. Natural comic timing but still learning the craft. Gen Z loves her, studio execs don't understand her.",
    visualDescription: "Quirky, expressive, meme-able face.",
    personality: ["Internet Famous", "Quick-Witted", "Anxious"],
    relationships: { a11: 30, a9: 15 },
  },
  {
    id: "a21",
    name: "Douglas 'Duke' Henderson",
    age: 62,
    gender: "Male",
    tier: ActorTier.CList,
    salary: 200000,
    reputation: 48,
    skill: 72,
    genres: [Genre.Action, Genre.Drama],
    img: "",
    status: "Available",
    bio: "Washed-up 70s action star. Did too many direct-to-video sequels in the 90s. Trying to get one last theatrical role before retirement.",
    visualDescription: "Still imposing, weathered face, holds onto the past.",
    personality: ["Nostalgic", "Proud", "Hoping for Comeback"],
    relationships: { a5: -10, a13: 20 },
  },
  {
    id: "a22",
    name: "Jasmine Okafor",
    age: 29,
    gender: "Female",
    tier: ActorTier.CList,
    salary: 210000,
    reputation: 56,
    skill: 74,
    genres: [Genre.Drama, Genre.Romance, Genre.Thriller],
    img: "",
    status: "Available",
    bio: "Soap opera veteran trying to transition to film. Has the chops but Hollywood hasn't noticed yet. Extremely dedicated to her craft.",
    visualDescription: "Soap opera glamorous, always camera ready.",
    personality: ["Dedicated", "Overlooked", "Persistent"],
    relationships: { a8: 15, a14: 20 },
  },
  {
    id: "a23",
    name: "Kevin 'K-Smooth' Johnson",
    age: 33,
    gender: "Male",
    tier: ActorTier.CList,
    salary: 190000,
    reputation: 54,
    skill: 60,
    genres: [Genre.Comedy, Genre.Action],
    img: "",
    status: "Available",
    bio: "Former rapper turned actor. Movies keep flopping but he keeps getting cast. More charisma than talent. Genuinely nice guy though.",
    visualDescription: "Street fashion, big smile, magnetic energy.",
    personality: ["Charismatic", "Limited Range", "Likeable"],
    relationships: { a11: 35, a15: 25 },
  },
  {
    id: "a24",
    name: "Margot Sullivan",
    age: 47,
    gender: "Female",
    tier: ActorTier.CList,
    salary: 240000,
    reputation: 59,
    skill: 80,
    genres: [Genre.Drama, Genre.Horror, Genre.Thriller],
    img: "",
    status: "Available",
    bio: "Former sitcom star reinventing herself. The mom from that 90s show everyone loved. Tired of being recognized for one role, ready for dramatic work.",
    visualDescription: "Sitcom mom energy, but with edge now.",
    personality: ["Reinventing", "Determined", "Typecast"],
    relationships: { a10: 25, a12: 15 },
  },

  // ========== INDIE DARLING (8 actors) ==========
  {
    id: "a25",
    name: "River Cassidy",
    age: 26,
    gender: "Male",
    tier: ActorTier.IndieDarling,
    salary: 150000,
    reputation: 68,
    skill: 85,
    genres: [Genre.Drama, Genre.Romance],
    img: "",
    status: "Available",
    bio: "Sundance darling who refuses studio work. Lives in a commune in Vermont. Critics call him a 'once-in-a-generation talent.' Might be too weird for mainstream.",
    visualDescription: "Ethereal, haunted eyes, androgynous beauty.",
    personality: ["Artistic", "Pretentious", "Genuinely Talented"],
    relationships: { a27: 40, a14: 30 },
  },
  {
    id: "a26",
    name: "Zoe Blackwood",
    age: 32,
    gender: "Female",
    tier: ActorTier.IndieDarling,
    salary: 175000,
    reputation: 72,
    skill: 88,
    genres: [Genre.Drama, Genre.Horror, Genre.Thriller],
    img: "",
    status: "Available",
    bio: "Fearless performer known for extreme transformations. Shaved her head twice, gained and lost 40 pounds for roles. Art-house favorite, mainstream hesitant.",
    visualDescription: "Chameleon, unrecognizable between roles.",
    personality: ["Fearless", "Method", "Unconventional"],
    relationships: { a12: 30, a6: 20 },
  },
  {
    id: "a27",
    name: "Ezra Moon",
    age: 29,
    gender: "Male",
    tier: ActorTier.IndieDarling,
    salary: 140000,
    reputation: 65,
    skill: 82,
    genres: [Genre.SciFi, Genre.Drama, Genre.Fantasy],
    img: "",
    status: "Available",
    bio: "Philosophy major who fell into acting. Every interview becomes a meditation on existence. Directors either love or hate working with him. No middle ground.",
    visualDescription: "Thoughtful, always seems elsewhere mentally.",
    personality: ["Philosophical", "Difficult", "Magnetic"],
    relationships: { a25: 40, a28: 25 },
  },
  {
    id: "a28",
    name: "Luna Estrella",
    age: 24,
    gender: "Female",
    tier: ActorTier.IndieDarling,
    salary: 130000,
    reputation: 64,
    skill: 79,
    genres: [Genre.Drama, Genre.Fantasy, Genre.Romance],
    img: "",
    status: "Available",
    bio: "Cannes discovery at 19, been working steadily in European cinema. American studios keep calling but she keeps saying no. Mystique is her brand.",
    visualDescription: "European elegance, otherworldly presence.",
    personality: ["Mysterious", "Selective", "International"],
    relationships: { a27: 25, a26: 30 },
  },
  {
    id: "a29",
    name: "Atlas Reed",
    age: 37,
    gender: "Male",
    tier: ActorTier.IndieDarling,
    salary: 165000,
    reputation: 70,
    skill: 86,
    genres: [Genre.Drama, Genre.Comedy, Genre.Thriller],
    img: "",
    status: "Available",
    bio: "Documentary filmmaker who started acting on a dare. Brings raw authenticity to every role. Hollywood keeps trying to polish him but he resists.",
    visualDescription: "Rugged, real, non-Hollywood energy.",
    personality: ["Authentic", "Anti-Hollywood", "Grounded"],
    relationships: { a25: 20, a19: 30 },
  },
  {
    id: "a30",
    name: "Iris Valentine",
    age: 41,
    gender: "Female",
    tier: ActorTier.IndieDarling,
    salary: 180000,
    reputation: 74,
    skill: 90,
    genres: [Genre.Drama, Genre.Thriller],
    img: "",
    status: "Available",
    bio: "Theater legend who does one film a year. Terrifies young actors with her intensity. Roger Ebert called her 'the best actress most people haven't seen.'",
    visualDescription: "Commanding, theatrical, intimidating.",
    personality: ["Intimidating", "Legendary", "Exacting"],
    relationships: { a6: 35, a17: 40 },
  },
  {
    id: "a31",
    name: "Phoenix Wilder",
    age: 22,
    gender: "Male",
    tier: ActorTier.IndieDarling,
    salary: 120000,
    reputation: 58,
    skill: 76,
    genres: [Genre.Drama, Genre.Horror],
    img: "",
    status: "Available",
    bio: "Breakout from a critically acclaimed indie horror. Born into Hollywood royalty but rejected it. Estranged from famous parent. Tabloid fodder with actual talent.",
    visualDescription: "Haunted, beautiful, troubled.",
    personality: ["Troubled", "Talented", "Running From Fame"],
    relationships: { a25: 30, a5: -40 },
  },
  {
    id: "a32",
    name: "Sage Morrison",
    age: 35,
    gender: "Female",
    tier: ActorTier.IndieDarling,
    salary: 155000,
    reputation: 67,
    skill: 84,
    genres: [Genre.Comedy, Genre.Drama, Genre.Romance],
    img: "",
    status: "Available",
    bio: "Improviser and playwright who acts in her own work. Creates ensemble pieces where she's rarely the lead. More interested in the art than the fame.",
    visualDescription: "Warm, approachable, creative energy.",
    personality: ["Collaborative", "Creative", "Ensemble Player"],
    relationships: { a29: 35, a30: 25 },
  },

  // ========== NEWCOMER (8 actors) ==========
  {
    id: "a33",
    name: "Jake Holloway",
    age: 21,
    gender: "Male",
    tier: ActorTier.Newcomer,
    salary: 75000,
    reputation: 35,
    skill: 55,
    genres: [Genre.Action, Genre.Comedy],
    img: "",
    status: "Available",
    bio: "Star quarterback who got discovered. Zero training, pure natural charisma. Agents are fighting over him. Might be the next big thing or flame out spectacularly.",
    visualDescription: "All-American, athletic, camera loves him.",
    personality: ["Raw Talent", "Cocky", "Untested"],
    relationships: { a9: 15 },
  },
  {
    id: "a34",
    name: "Maya Santos",
    age: 19,
    gender: "Female",
    tier: ActorTier.Newcomer,
    salary: 65000,
    reputation: 40,
    skill: 70,
    genres: [Genre.Drama, Genre.Romance],
    img: "",
    status: "Available",
    bio: "Won a nationwide talent search. First role ever and she's already getting Oscar buzz. Either the real deal or the most overhyped newcomer in years.",
    visualDescription: "Fresh-faced, innocent, surprising depth.",
    personality: ["Promising", "Overwhelmed", "Natural"],
    relationships: { a2: 10 },
  },
  {
    id: "a35",
    name: "Brandon Liu",
    age: 24,
    gender: "Male",
    tier: ActorTier.Newcomer,
    salary: 80000,
    reputation: 38,
    skill: 62,
    genres: [Genre.SciFi, Genre.Action, Genre.Comedy],
    img: "",
    status: "Available",
    bio: "Martial arts champion who wants to be an actor. Has the skills but still learning to emote. Working with an acting coach between training sessions.",
    visualDescription: "Athletic, focused, work in progress.",
    personality: ["Dedicated", "Stiff", "Hardworking"],
    relationships: { a3: 20 },
  },
  {
    id: "a36",
    name: "Emma Thornton",
    age: 23,
    gender: "Female",
    tier: ActorTier.Newcomer,
    salary: 70000,
    reputation: 42,
    skill: 68,
    genres: [Genre.Horror, Genre.Thriller, Genre.Drama],
    img: "",
    status: "Available",
    bio: "Theater school valedictorian thrown into Hollywood. Classically trained but adapting to screen. Directors say she's 'almost there.' Whatever that means.",
    visualDescription: "Polished, trained, trying to unlearn technique.",
    personality: ["Trained", "Anxious", "Adapting"],
    relationships: { a6: 15, a17: 20 },
  },
  {
    id: "a37",
    name: "Diego Reyes",
    age: 26,
    gender: "Male",
    tier: ActorTier.Newcomer,
    salary: 85000,
    reputation: 45,
    skill: 58,
    genres: [Genre.Romance, Genre.Drama, Genre.Comedy],
    img: "",
    status: "Available",
    bio: "Telenovela star trying to cross over. Huge following in Latin America, unknown in the US. Charming as hell but his English needs work.",
    visualDescription: "Soap opera handsome, magnetic, accent heavy.",
    personality: ["Charming", "Determined", "Fish Out of Water"],
    relationships: { a11: 25 },
  },
  {
    id: "a38",
    name: "Lily Park",
    age: 20,
    gender: "Female",
    tier: ActorTier.Newcomer,
    salary: 60000,
    reputation: 32,
    skill: 64,
    genres: [Genre.Comedy, Genre.Romance, Genre.Fantasy],
    img: "",
    status: "Available",
    bio: "K-pop idol making the jump to Hollywood. Massive international fanbase but acting skeptics abound. More talented than people expect.",
    visualDescription: "Pop star polished, perfected image.",
    personality: ["Trained", "Disciplined", "More Than Expected"],
    relationships: { a20: 20 },
  },
  {
    id: "a39",
    name: "Marcus Webb",
    age: 28,
    gender: "Male",
    tier: ActorTier.Newcomer,
    salary: 90000,
    reputation: 44,
    skill: 72,
    genres: [Genre.Drama, Genre.Thriller],
    img: "",
    status: "Available",
    bio: "Former marine with a face for drama. Discovered at a VA hospital by a casting director. Brings intense authenticity to military and trauma roles.",
    visualDescription: "Thousand-yard stare, intimidating presence.",
    personality: ["Intense", "Authentic", "Haunted"],
    relationships: { a19: 25, a29: 15 },
  },
  {
    id: "a40",
    name: "Chloe Anderson",
    age: 22,
    gender: "Female",
    tier: ActorTier.Newcomer,
    salary: 55000,
    reputation: 30,
    skill: 60,
    genres: [Genre.Comedy, Genre.Romance],
    img: "",
    status: "Available",
    bio: "TikTok star with 10 million followers. Studios think she's the key to Gen Z. Critics think she's a gimmick. Truth is probably somewhere in between.",
    visualDescription: "Internet-ready, constant content creator.",
    personality: ["Social Media Native", "Self-Aware", "Hustler"],
    relationships: { a20: 30 },
  },
];

export const SEED_SCRIPTS: Script[] = [
  {
    id: "s1",
    title: "Memory Lane",
    genre: Genre.Romance,
    quality: 92,
    complexity: 85,
    baseCost: 800000,
    currentBid: 800000,
    highBidderId: null,
    description:
      "Two strangers meet at a memory clinic where people can selectively erase painful experiences. As they fall in love, they must decide if forgetting the past is worth losing their future.",
    tagline: "Some memories are worth keeping.",
    requiredCast: 2,
    tone: "Melancholic",
  },
  {
    id: "s2",
    title: "The Double Cross",
    genre: Genre.Thriller,
    quality: 95,
    complexity: 90,
    baseCost: 1200000,
    currentBid: 1200000,
    highBidderId: null,
    description:
      "A detective infiltrates a crime syndicate while unknowingly hunting another undercover agent. When their identities collide, loyalty becomes a deadly game.",
    tagline: "Trust no one. Suspect everyone.",
    requiredCast: 3,
    tone: "Serious",
  },
  {
    id: "s3",
    title: "Road to Starlight",
    genre: Genre.Comedy,
    quality: 88,
    complexity: 65,
    baseCost: 450000,
    currentBid: 450000,
    highBidderId: null,
    description:
      "A dysfunctional family embarks on a chaotic cross-country road trip to support their youngest member's dream of competing in a national talent show.",
    tagline: "Every family has its bumps.",
    requiredCast: 2,
    tone: "Lighthearted",
  },
  {
    id: "s4",
    title: "Desert Fortune",
    genre: Genre.Thriller,
    quality: 96,
    complexity: 88,
    baseCost: 950000,
    currentBid: 950000,
    highBidderId: null,
    description:
      "A welder stumbles upon a briefcase full of cash in the desert, triggering a cat-and-mouse chase with a relentless hitman who never stops hunting.",
    tagline: "Some money costs more than it's worth.",
    requiredCast: 2,
    tone: "Serious",
  },
  {
    id: "s5",
    title: "Last Night Out",
    genre: Genre.Comedy,
    quality: 82,
    complexity: 55,
    baseCost: 350000,
    currentBid: 350000,
    highBidderId: null,
    description:
      "Two best friends attempt one final epic party before graduating high school, but everything that can go wrong does.",
    tagline: "One night. Zero limits.",
    requiredCast: 2,
    tone: "Lighthearted",
  },
  {
    id: "s6",
    title: "Black Gold",
    genre: Genre.Drama,
    quality: 98,
    complexity: 92,
    baseCost: 1500000,
    currentBid: 1500000,
    highBidderId: null,
    description:
      "An oil prospector's ruthless ambition destroys everyone around him as he builds an empire in the California desert at the turn of the century.",
    tagline: "Greed has no limits.",
    requiredCast: 2,
    tone: "Serious",
  },
  {
    id: "s7",
    title: "Nine Months Later",
    genre: Genre.Comedy,
    quality: 85,
    complexity: 60,
    baseCost: 400000,
    currentBid: 400000,
    highBidderId: null,
    description:
      "A quirky teenager navigates an unexpected pregnancy with humor and heart, finding family in the most unlikely places.",
    tagline: "Growing up happens faster than you think.",
    requiredCast: 2,
    tone: "Lighthearted",
  },
  {
    id: "s8",
    title: "The Illusionists",
    genre: Genre.Thriller,
    quality: 90,
    complexity: 87,
    baseCost: 750000,
    currentBid: 750000,
    highBidderId: null,
    description:
      "Two rival magicians in Victorian London become obsessed with creating the perfect trick, sacrificing everything in their dangerous competition.",
    tagline: "Every great magic trick has a price.",
    requiredCast: 2,
    tone: "Serious",
  },
  {
    id: "s9",
    title: "The Faun's Maze",
    genre: Genre.Fantasy,
    quality: 94,
    complexity: 85,
    baseCost: 900000,
    currentBid: 900000,
    highBidderId: null,
    description:
      "A young girl escapes into a dark fairy tale world to cope with the horrors of war-torn Spain, where mythical creatures offer both danger and salvation.",
    tagline: "Where nightmares and fairy tales meet.",
    requiredCast: 2,
    tone: "Dark",
  },
  {
    id: "s10",
    title: "Million Dollar Question",
    genre: Genre.Drama,
    quality: 91,
    complexity: 78,
    baseCost: 650000,
    currentBid: 650000,
    highBidderId: null,
    description:
      "A street kid from Mumbai becomes a game show sensation, but his incredible winning streak leads to accusations of cheating and a journey through his extraordinary past.",
    tagline: "Every answer tells a story.",
    requiredCast: 2,
    tone: "Uplifting",
  },
  {
    id: "s11",
    title: "The Ghost Protocol",
    genre: Genre.Action,
    quality: 87,
    complexity: 75,
    baseCost: 600000,
    currentBid: 600000,
    highBidderId: null,
    description:
      "An amnesiac operative washes ashore with no memory but deadly skills. As assassins close in, he must piece together his identity before it's too late.",
    tagline: "He doesn't know who he is. They know who he was.",
    requiredCast: 2,
    tone: "Serious",
  },
  {
    id: "s12",
    title: "Unexpected Delivery",
    genre: Genre.Romance,
    quality: 78,
    complexity: 50,
    baseCost: 300000,
    currentBid: 300000,
    highBidderId: null,
    description:
      "A one-night stand turns into a nine-month commitment when two polar opposites must figure out if they can build a relationship while building a family.",
    tagline: "Life's biggest surprise.",
    requiredCast: 2,
    tone: "Lighthearted",
  },
];
