import { Actor, ActorTier, Genre, Script, RivalStudio } from "./types";

export const INITIAL_BALANCE = 5000000;
export const START_YEAR = 2003;
export const START_MONTH = 1;

export const GENRES = Object.values(Genre);

const STUDIO_NAMES = [
  "Metro-G-M",
  "Global-Universal",
  "IndieCloud Pictures",
  "Paramount-ish",
  "Warner-Brothers-ish",
  "Sony-ish Entertainment",
  "Disney-ish Films",
  "Miramax-alike",
  "New Line-alike",
  "Lionsgate-ish",
  "Summit-alike",
  "Fox-ish Searchlight",
  "Focus-ish Features",
  "A24-proto",
  "Dimension-alike",
  "DreamWorks-ish",
  "Pixar-ish Animation",
  "Castle Rock-ish",
  "Orion-ish",
  "Touchstone-ish",
  "New Line-ish",
  "PolyGram-ish",
  "MGM-ish",
  "Screen Gems-ish",
  "Tristar-ish",
  "Hollywood-ish Pictures",
  "Working Title-ish",
  "Imagine-ish",
  "Amblin-ish",
  "Village-Roadshow-ish",
];

const PERSONALITIES: RivalStudio["personality"][] = [
  "Aggressive",
  "Friendly",
  "Elitist",
  "Chaotic",
];

export const RIVAL_STUDIOS: RivalStudio[] = STUDIO_NAMES.map((name, i) => ({
  id: `r${i}`,
  name,
  reputation: 30 + Math.floor(Math.random() * 60),
  balance: 5000000 + Math.floor(Math.random() * 95000000),
  yearlyRevenue: 0,
  color: `hsl(${i * 12}, 70%, 40%)`,
  personality: PERSONALITIES[Math.floor(Math.random() * PERSONALITIES.length)],
  relationship: 0,
  ownedActors: [],
  ownedScripts: [],
  activeProjects: [],
}));

export const SEED_ACTORS: Actor[] = [
  {
    id: "a1",
    name: "Brad Fitt",
    age: 38,
    gender: "Male",
    tier: ActorTier.AList,
    salary: 2000000,
    reputation: 95,
    skill: 90,
    genres: [Genre.Action, Genre.Drama],
    img: "https://picsum.photos/100/100?random=1",
    status: "Available",
    bio: "The biggest heartthrob of the early 2000s. Known for eating in every scene.",
    visualDescription:
      "Chiseled jawline, frosted tips, wears aviators indoors.",
    personality: ["Charismatic", "Hungry"],
    relationships: { a2: 25, a3: 10 },
  },
  {
    id: "a2",
    name: "Julia Roberts-ish",
    age: 35,
    gender: "Female",
    tier: ActorTier.AList,
    salary: 2200000,
    reputation: 98,
    skill: 88,
    genres: [Genre.Romance, Genre.Comedy],
    img: "https://picsum.photos/100/100?random=2",
    status: "Available",
    bio: "America's sweetheart with a million dollar smile and a chaotic laugh.",
    visualDescription: "Auburn curls, wide smile, often wears polka dots.",
    personality: ["Diva", "Perfectionist"],
    relationships: { a1: 25, a5: 15 },
  },
  {
    id: "a3",
    name: "Keanu Reeves-alike",
    age: 39,
    gender: "Male",
    tier: ActorTier.AList,
    salary: 1800000,
    reputation: 92,
    skill: 75,
    genres: [Genre.SciFi, Genre.Action],
    img: "https://picsum.photos/100/100?random=3",
    status: "Available",
    bio: "A man of few words but many martial arts moves.",
    visualDescription:
      "Sleek black hair, trench coat enthusiast, stoic expression.",
    personality: ["Humble", "Stoic"],
    relationships: { a1: 10, a4: -5 },
  },
  {
    id: "a4",
    name: "Angelina J-ish",
    age: 28,
    gender: "Female",
    tier: ActorTier.AList,
    salary: 1900000,
    reputation: 94,
    skill: 85,
    genres: [Genre.Action, Genre.Drama],
    img: "https://picsum.photos/100/100?random=4",
    status: "Available",
    bio: "The ultimate action queen. Mysterious, intense, and loves vials of blood.",
    visualDescription: "Full lips, leather-clad, looks ready for a heist.",
    personality: ["Intense", "Mysterious"],
    relationships: { a1: 5, a3: -10 },
  },
  {
    id: "a5",
    name: "Tom C-ish",
    age: 41,
    gender: "Male",
    tier: ActorTier.AList,
    salary: 2500000,
    reputation: 99,
    skill: 92,
    genres: [Genre.Action, Genre.Drama],
    img: "https://picsum.photos/100/100?random=5",
    status: "Available",
    bio: "Does his own stunts. Always running. Might jump on your couch.",
    visualDescription:
      "Intense grin, cockpit-ready, shorter than he looks on screen.",
    personality: ["Driven", "Unstoppable"],
    relationships: { a2: 15, a1: 0 },
  },
];

export const SEED_SCRIPTS: Script[] = [
  {
    id: "s1",
    title: "Memory Lane",
    genre: Genre.Romance,
    quality: 92,
    complexity: 85,
    baseCost: 800000,
    currentBid: 800000,
    highBidderId: null,
    description:
      "Two strangers meet at a memory clinic where people can selectively erase painful experiences. As they fall in love, they must decide if forgetting the past is worth losing their future.",
    tagline: "Some memories are worth keeping.",
    requiredCast: 2,
    tone: "Melancholic",
  },
  {
    id: "s2",
    title: "The Double Cross",
    genre: Genre.Thriller,
    quality: 95,
    complexity: 90,
    baseCost: 1200000,
    currentBid: 1200000,
    highBidderId: null,
    description:
      "A detective infiltrates a crime syndicate while unknowingly hunting another undercover agent. When their identities collide, loyalty becomes a deadly game.",
    tagline: "Trust no one. Suspect everyone.",
    requiredCast: 3,
    tone: "Serious",
  },
  {
    id: "s3",
    title: "Road to Starlight",
    genre: Genre.Comedy,
    quality: 88,
    complexity: 65,
    baseCost: 450000,
    currentBid: 450000,
    highBidderId: null,
    description:
      "A dysfunctional family embarks on a chaotic cross-country road trip to support their youngest member's dream of competing in a national talent show.",
    tagline: "Every family has its bumps.",
    requiredCast: 2,
    tone: "Lighthearted",
  },
  {
    id: "s4",
    title: "Desert Fortune",
    genre: Genre.Thriller,
    quality: 96,
    complexity: 88,
    baseCost: 950000,
    currentBid: 950000,
    highBidderId: null,
    description:
      "A welder stumbles upon a briefcase full of cash in the desert, triggering a cat-and-mouse chase with a relentless hitman who never stops hunting.",
    tagline: "Some money costs more than it's worth.",
    requiredCast: 2,
    tone: "Serious",
  },
  {
    id: "s5",
    title: "Last Night Out",
    genre: Genre.Comedy,
    quality: 82,
    complexity: 55,
    baseCost: 350000,
    currentBid: 350000,
    highBidderId: null,
    description:
      "Two best friends attempt one final epic party before graduating high school, but everything that can go wrong does.",
    tagline: "One night. Zero limits.",
    requiredCast: 2,
    tone: "Lighthearted",
  },
  {
    id: "s6",
    title: "Black Gold",
    genre: Genre.Drama,
    quality: 98,
    complexity: 92,
    baseCost: 1500000,
    currentBid: 1500000,
    highBidderId: null,
    description:
      "An oil prospector's ruthless ambition destroys everyone around him as he builds an empire in the California desert at the turn of the century.",
    tagline: "Greed has no limits.",
    requiredCast: 2,
    tone: "Serious",
  },
  {
    id: "s7",
    title: "Nine Months Later",
    genre: Genre.Comedy,
    quality: 85,
    complexity: 60,
    baseCost: 400000,
    currentBid: 400000,
    highBidderId: null,
    description:
      "A quirky teenager navigates an unexpected pregnancy with humor and heart, finding family in the most unlikely places.",
    tagline: "Growing up happens faster than you think.",
    requiredCast: 2,
    tone: "Lighthearted",
  },
  {
    id: "s8",
    title: "The Illusionists",
    genre: Genre.Thriller,
    quality: 90,
    complexity: 87,
    baseCost: 750000,
    currentBid: 750000,
    highBidderId: null,
    description:
      "Two rival magicians in Victorian London become obsessed with creating the perfect trick, sacrificing everything in their dangerous competition.",
    tagline: "Every great magic trick has a price.",
    requiredCast: 2,
    tone: "Serious",
  },
  {
    id: "s9",
    title: "The Faun's Maze",
    genre: Genre.Fantasy,
    quality: 94,
    complexity: 85,
    baseCost: 900000,
    currentBid: 900000,
    highBidderId: null,
    description:
      "A young girl escapes into a dark fairy tale world to cope with the horrors of war-torn Spain, where mythical creatures offer both danger and salvation.",
    tagline: "Where nightmares and fairy tales meet.",
    requiredCast: 2,
    tone: "Dark",
  },
  {
    id: "s10",
    title: "Million Dollar Question",
    genre: Genre.Drama,
    quality: 91,
    complexity: 78,
    baseCost: 650000,
    currentBid: 650000,
    highBidderId: null,
    description:
      "A street kid from Mumbai becomes a game show sensation, but his incredible winning streak leads to accusations of cheating and a journey through his extraordinary past.",
    tagline: "Every answer tells a story.",
    requiredCast: 2,
    tone: "Uplifting",
  },
  {
    id: "s11",
    title: "The Ghost Protocol",
    genre: Genre.Action,
    quality: 87,
    complexity: 75,
    baseCost: 600000,
    currentBid: 600000,
    highBidderId: null,
    description:
      "An amnesiac operative washes ashore with no memory but deadly skills. As assassins close in, he must piece together his identity before it's too late.",
    tagline: "He doesn't know who he is. They know who he was.",
    requiredCast: 2,
    tone: "Serious",
  },
  {
    id: "s12",
    title: "Unexpected Delivery",
    genre: Genre.Romance,
    quality: 78,
    complexity: 50,
    baseCost: 300000,
    currentBid: 300000,
    highBidderId: null,
    description:
      "A one-night stand turns into a nine-month commitment when two polar opposites must figure out if they can build a relationship while building a family.",
    tagline: "Life's biggest surprise.",
    requiredCast: 2,
    tone: "Lighthearted",
  },
];
