-- Remove duplicate owned scripts, keeping the most recent one
WITH duplicates AS (
  SELECT id,
         ROW_NUMBER() OVER (
           PARTITION BY user_id, script_id 
           ORDER BY created_at DESC
         ) as row_num
  FROM owned_scripts
)
DELETE FROM owned_scripts
WHERE id IN (
  SELECT id FROM duplicates WHERE row_num > 1
);

-- Also clean up duplicate "Script Acquired" events generated by the bug
WITH duplicate_events AS (
  SELECT id,
         ROW_NUMBER() OVER (
           PARTITION BY user_id, title, description, month, year
           ORDER BY created_at DESC
         ) as row_num
  FROM game_events
  WHERE title = 'SCRIPT ACQUIRED'
)
DELETE FROM game_events
WHERE id IN (
  SELECT id FROM duplicate_events WHERE row_num > 1
);
