-- Full Game Reset Script
-- RESET WARNING: THIS WILL WIPE ALL PROGRESS

BEGIN;

-- 1. Truncate Tables
TRUNCATE TABLE game_events, notifications, projects, owned_scripts, bids RESTART IDENTITY CASCADE;

-- 2. Reset Global Clock (Jan 1, 2003)
UPDATE global_game_clock 
SET month = 1, year = 2003, last_advanced_at = NOW() 
WHERE id = 1;

-- 3. Reset Studios Balance
UPDATE studios SET balance = 5000000;

-- 4. Reset Actors (Delete All)
DELETE FROM actors;

-- 5. Insert Seed Actors
INSERT INTO actors (
    id, name, age, gender, tier, salary, reputation, skill, 
    genres, status, bio, visual_description, personality, relationships, gossip
) VALUES
(
        'a1', 
        'Marcus Sterling', 
        42, 
        'Male', 
        'A-List', 
        2500000, 
        98, 
        92, 
        '["Action","Drama"]', 
        'Available', 
        'Three-time Academy nominee known for intense method acting. Once lived in a monastery for 6 months to prepare for a role. Refuses to do press junkets.', 
        'Salt-and-pepper hair, intense blue eyes, always wears black.', 
        '["Method Actor","Reclusive","Perfectionist"]', 
        '{"a3":30,"a7":-20}', 
        '[]'::jsonb
    ),
(
        'a2', 
        'Vivienne Cross', 
        34, 
        'Female', 
        'A-List', 
        2200000, 
        96, 
        90, 
        '["Romance","Drama","Comedy"]', 
        'Available', 
        'America''s sweetheart turned serious actress. Started in teen comedies, now dominates awards season. Known for her infectious laugh and fierce contract negotiations.', 
        'Radiant smile, auburn hair, designer everything.', 
        '["Charismatic","Business-Savvy","Demanding"]', 
        '{"a5":45,"a8":20}', 
        '[]'::jsonb
    ),
(
        'a3', 
        'Damien Locke', 
        38, 
        'Male', 
        'A-List', 
        2100000, 
        94, 
        88, 
        '["Sci-Fi","Action","Thriller"]', 
        'Available', 
        'Former stuntman turned leading man. Does all his own stunts and has broken 23 bones on set. Extremely superstitious—won''t start filming on Tuesdays.', 
        'Rugged features, visible scars, athletic build.', 
        '["Daredevil","Superstitious","Loyal"]', 
        '{"a1":30,"a6":15}', 
        '[]'::jsonb
    ),
(
        'a4', 
        'Celeste Monroe', 
        29, 
        'Female', 
        'A-List', 
        1900000, 
        95, 
        86, 
        '["Action","Thriller","Sci-Fi"]', 
        'Available', 
        'The reigning action queen. Trained in three martial arts and speaks five languages. Tabloids love her mysterious personal life and rumored feuds.', 
        'Striking features, always camera-ready, athletic.', 
        '["Fierce","Private","Competitive"]', 
        '{"a2":-15,"a9":25}', 
        '[]'::jsonb
    ),
(
        'a5', 
        'Harrison Blake', 
        55, 
        'Male', 
        'A-List', 
        2800000, 
        99, 
        94, 
        '["Action","Drama","Sci-Fi"]', 
        'Available', 
        'Living legend. Four decades of iconic roles. Known for improvising his best lines. Once punched a director and somehow became more famous.', 
        'Weathered charm, graying temples, sardonic grin.', 
        '["Legendary","Unpredictable","Gruff"]', 
        '{"a2":45,"a1":10}', 
        '[]'::jsonb
    ),
(
        'a6', 
        'Natasha Vance', 
        31, 
        'Female', 
        'A-List', 
        2000000, 
        93, 
        91, 
        '["Drama","Romance","Thriller"]', 
        'Available', 
        'Stage actress who conquered Hollywood. Tony winner at 24, Oscar winner at 28. Known for transformative performances and absolutely zero tolerance for mediocrity.', 
        'Elegant, expressive eyes, theatrical presence.', 
        '["Theatrical","Demanding","Brilliant"]', 
        '{"a3":15,"a12":35}', 
        '[]'::jsonb
    ),
(
        'a7', 
        'Derek Chambers', 
        45, 
        'Male', 
        'B-List', 
        800000, 
        75, 
        82, 
        '["Action","Comedy"]', 
        'Available', 
        'Former action star trying to transition to comedy. Had a messy divorce that tanked his reputation. Currently on a redemption arc the tabloids love to cover.', 
        'Still fit, dad jokes energy, trying too hard.', 
        '["Insecure","Desperate","Actually Funny"]', 
        '{"a1":-20,"a15":30}', 
        '[]'::jsonb
    ),
(
        'a8', 
        'Miranda Chen', 
        36, 
        'Female', 
        'B-List', 
        750000, 
        78, 
        85, 
        '["Drama","Thriller","Horror"]', 
        'Available', 
        'Critically acclaimed but never quite breaks through to the A-list. Industry insiders say she''s ''one role away'' from superstardom. Has been ''one role away'' for five years.', 
        'Understated elegance, always looks thoughtful.', 
        '["Underrated","Patient","Quietly Ambitious"]', 
        '{"a2":20,"a6":25}', 
        '[]'::jsonb
    ),
(
        'a9', 
        'Tyler Finn', 
        27, 
        'Male', 
        'B-List', 
        650000, 
        80, 
        72, 
        '["Romance","Comedy","Drama"]', 
        'Available', 
        'Teen heartthrob aging out of his niche. Trying to be taken seriously but keeps getting cast as ''the boyfriend.'' Has a problematic stan culture following him around.', 
        'Pretty boy looks, perfect hair, puppy dog eyes.', 
        '["Charming","Naive","People Pleaser"]', 
        '{"a4":25,"a11":-10}', 
        '[]'::jsonb
    ),
(
        'a10', 
        'Josephine Hart', 
        48, 
        'Female', 
        'B-List', 
        700000, 
        82, 
        89, 
        '["Drama","Thriller"]', 
        'Available', 
        'Character actress who steals every scene. Oscar-nominated for supporting roles three times. Directors fight to get her for ''the mom who reveals a dark secret.''', 
        'Distinguished, maternal warmth hiding steel.', 
        '["Scene-Stealer","Generous","Wise"]', 
        '{"a5":20,"a6":30}', 
        '[]'::jsonb
    ),
(
        'a11', 
        'Ricky Delgado', 
        33, 
        'Male', 
        'B-List', 
        600000, 
        73, 
        78, 
        '["Comedy","Action","Romance"]', 
        'Available', 
        'SNL alumnus who made the jump to films. Known for explosive energy and absolutely chaotic talk show appearances. May or may not have a gambling problem.', 
        'Animated expressions, wild energy, always moving.', 
        '["Manic","Hilarious","Self-Destructive"]', 
        '{"a9":-10,"a15":40}', 
        '[]'::jsonb
    ),
(
        'a12', 
        'Elizabeth Frost', 
        40, 
        'Female', 
        'B-List', 
        850000, 
        84, 
        87, 
        '["Horror","Thriller","Drama"]', 
        'Available', 
        'Scream queen who''s evolved into a genre icon. Producers know if she''s in a horror film, it''s quality. Runs a popular horror podcast in her spare time.', 
        'Striking, can go from girl-next-door to terrifying.', 
        '["Genre-Savvy","Professional","Secretly Nerdy"]', 
        '{"a6":35,"a8":20}', 
        '[]'::jsonb
    ),
(
        'a13', 
        'Vincent Cole', 
        52, 
        'Male', 
        'B-List', 
        700000, 
        76, 
        84, 
        '["Drama","Thriller","Sci-Fi"]', 
        'Available', 
        'Once A-list in the 80s, now a reliable character actor. Has made peace with his faded fame and genuinely enjoys the work. Kids don''t know him but their parents do.', 
        'Distinguished, silver fox, carries gravitas.', 
        '["Humble","Professional","Nostalgic"]', 
        '{"a5":15,"a1":5}', 
        '[]'::jsonb
    ),
(
        'a14', 
        'Simone Baptiste', 
        28, 
        'Female', 
        'B-List', 
        550000, 
        77, 
        80, 
        '["Romance","Drama","Comedy"]', 
        'Available', 
        'Rising star from indie darling to mainstream recognition. Critics adore her, audiences are catching on. Known for choosing interesting projects over paychecks.', 
        'Natural beauty, expressive, effortlessly cool.', 
        '["Artistic","Selective","Authentic"]', 
        '{"a2":15,"a19":25}', 
        '[]'::jsonb
    ),
(
        'a15', 
        'Chuck Martinez', 
        44, 
        'Male', 
        'C-List', 
        250000, 
        55, 
        70, 
        '["Action","Comedy"]', 
        'Available', 
        'The guy you recognize but can''t name. Been in 47 movies, usually as ''Cop #2'' or ''Guy in Bar.'' Somehow has a cult following for his cameos.', 
        'Generic leading man look, forgettable but likeable.', 
        '["Everyman","Hardworking","Self-Aware"]', 
        '{"a7":30,"a11":40}', 
        '[]'::jsonb
    ),
(
        'a16', 
        'Tiffany Marlowe', 
        26, 
        'Female', 
        'C-List', 
        200000, 
        60, 
        65, 
        '["Horror","Romance"]', 
        'Available', 
        'Former model trying to break into acting. More famous for who she''s dated than her roles. Actually more talented than people give her credit for.', 
        'Model gorgeous, knows her angles, underestimated.', 
        '["Underestimated","Ambitious","Resilient"]', 
        '{"a9":20,"a4":-25}', 
        '[]'::jsonb
    ),
(
        'a17', 
        'Bernard ''Bernie'' Walsh', 
        58, 
        'Male', 
        'C-List', 
        180000, 
        52, 
        75, 
        '["Drama","Comedy"]', 
        'Available', 
        'Theater veteran who never made it big in Hollywood. Does one film a year to pay for his passion projects. Students study his stage work.', 
        'Shakespearean bearing, voice like velvet.', 
        '["Theatrical","Bitter","Talented"]', 
        '{"a6":10,"a13":25}', 
        '[]'::jsonb
    ),
(
        'a18', 
        'Crystal Powers', 
        31, 
        'Female', 
        'C-List', 
        220000, 
        58, 
        62, 
        '["Action","Sci-Fi"]', 
        'Available', 
        'Former fitness influencer turned actress. Takes every action role she can get. Actually does train harder than most stunt doubles.', 
        'Incredibly fit, Instagram-ready, determined.', 
        '["Disciplined","Social Media Obsessed","Driven"]', 
        '{"a4":15,"a16":-10}', 
        '[]'::jsonb
    ),
(
        'a19', 
        'Omar Hassan', 
        35, 
        'Male', 
        'C-List', 
        230000, 
        63, 
        78, 
        '["Drama","Thriller"]', 
        'Available', 
        'British-trained actor struggling in Hollywood. Gets typecast constantly but delivers powerful performances anyway. One good role away from breaking out.', 
        'Intense gaze, commanding presence, frustrated.', 
        '["Frustrated","Talented","Determined"]', 
        '{"a14":25,"a1":5}', 
        '[]'::jsonb
    ),
(
        'a20', 
        'Penny Nguyen', 
        24, 
        'Female', 
        'C-List', 
        175000, 
        50, 
        68, 
        '["Comedy","Romance"]', 
        'Available', 
        'YouTube comedian who got a movie deal. Natural comic timing but still learning the craft. Gen Z loves her, studio execs don''t understand her.', 
        'Quirky, expressive, meme-able face.', 
        '["Internet Famous","Quick-Witted","Anxious"]', 
        '{"a11":30,"a9":15}', 
        '[]'::jsonb
    ),
(
        'a21', 
        'Douglas ''Duke'' Henderson', 
        62, 
        'Male', 
        'C-List', 
        200000, 
        48, 
        72, 
        '["Action","Drama"]', 
        'Available', 
        'Washed-up 70s action star. Did too many direct-to-video sequels in the 90s. Trying to get one last theatrical role before retirement.', 
        'Still imposing, weathered face, holds onto the past.', 
        '["Nostalgic","Proud","Hoping for Comeback"]', 
        '{"a5":-10,"a13":20}', 
        '[]'::jsonb
    ),
(
        'a22', 
        'Jasmine Okafor', 
        29, 
        'Female', 
        'C-List', 
        210000, 
        56, 
        74, 
        '["Drama","Romance","Thriller"]', 
        'Available', 
        'Soap opera veteran trying to transition to film. Has the chops but Hollywood hasn''t noticed yet. Extremely dedicated to her craft.', 
        'Soap opera glamorous, always camera ready.', 
        '["Dedicated","Overlooked","Persistent"]', 
        '{"a8":15,"a14":20}', 
        '[]'::jsonb
    ),
(
        'a23', 
        'Kevin ''K-Smooth'' Johnson', 
        33, 
        'Male', 
        'C-List', 
        190000, 
        54, 
        60, 
        '["Comedy","Action"]', 
        'Available', 
        'Former rapper turned actor. Movies keep flopping but he keeps getting cast. More charisma than talent. Genuinely nice guy though.', 
        'Street fashion, big smile, magnetic energy.', 
        '["Charismatic","Limited Range","Likeable"]', 
        '{"a11":35,"a15":25}', 
        '[]'::jsonb
    ),
(
        'a24', 
        'Margot Sullivan', 
        47, 
        'Female', 
        'C-List', 
        240000, 
        59, 
        80, 
        '["Drama","Horror","Thriller"]', 
        'Available', 
        'Former sitcom star reinventing herself. The mom from that 90s show everyone loved. Tired of being recognized for one role, ready for dramatic work.', 
        'Sitcom mom energy, but with edge now.', 
        '["Reinventing","Determined","Typecast"]', 
        '{"a10":25,"a12":15}', 
        '[]'::jsonb
    ),
(
        'a25', 
        'River Cassidy', 
        26, 
        'Male', 
        'Indie Darling', 
        150000, 
        68, 
        85, 
        '["Drama","Romance"]', 
        'Available', 
        'Sundance darling who refuses studio work. Lives in a commune in Vermont. Critics call him a ''once-in-a-generation talent.'' Might be too weird for mainstream.', 
        'Ethereal, haunted eyes, androgynous beauty.', 
        '["Artistic","Pretentious","Genuinely Talented"]', 
        '{"a27":40,"a14":30}', 
        '[]'::jsonb
    ),
(
        'a26', 
        'Zoe Blackwood', 
        32, 
        'Female', 
        'Indie Darling', 
        175000, 
        72, 
        88, 
        '["Drama","Horror","Thriller"]', 
        'Available', 
        'Fearless performer known for extreme transformations. Shaved her head twice, gained and lost 40 pounds for roles. Art-house favorite, mainstream hesitant.', 
        'Chameleon, unrecognizable between roles.', 
        '["Fearless","Method","Unconventional"]', 
        '{"a12":30,"a6":20}', 
        '[]'::jsonb
    ),
(
        'a27', 
        'Ezra Moon', 
        29, 
        'Male', 
        'Indie Darling', 
        140000, 
        65, 
        82, 
        '["Sci-Fi","Drama","Fantasy"]', 
        'Available', 
        'Philosophy major who fell into acting. Every interview becomes a meditation on existence. Directors either love or hate working with him. No middle ground.', 
        'Thoughtful, always seems elsewhere mentally.', 
        '["Philosophical","Difficult","Magnetic"]', 
        '{"a25":40,"a28":25}', 
        '[]'::jsonb
    ),
(
        'a28', 
        'Luna Estrella', 
        24, 
        'Female', 
        'Indie Darling', 
        130000, 
        64, 
        79, 
        '["Drama","Fantasy","Romance"]', 
        'Available', 
        'Cannes discovery at 19, been working steadily in European cinema. American studios keep calling but she keeps saying no. Mystique is her brand.', 
        'European elegance, otherworldly presence.', 
        '["Mysterious","Selective","International"]', 
        '{"a27":25,"a26":30}', 
        '[]'::jsonb
    ),
(
        'a29', 
        'Atlas Reed', 
        37, 
        'Male', 
        'Indie Darling', 
        165000, 
        70, 
        86, 
        '["Drama","Comedy","Thriller"]', 
        'Available', 
        'Documentary filmmaker who started acting on a dare. Brings raw authenticity to every role. Hollywood keeps trying to polish him but he resists.', 
        'Rugged, real, non-Hollywood energy.', 
        '["Authentic","Anti-Hollywood","Grounded"]', 
        '{"a25":20,"a19":30}', 
        '[]'::jsonb
    ),
(
        'a30', 
        'Iris Valentine', 
        41, 
        'Female', 
        'Indie Darling', 
        180000, 
        74, 
        90, 
        '["Drama","Thriller"]', 
        'Available', 
        'Theater legend who does one film a year. Terrifies young actors with her intensity. Roger Ebert called her ''the best actress most people haven''t seen.''', 
        'Commanding, theatrical, intimidating.', 
        '["Intimidating","Legendary","Exacting"]', 
        '{"a6":35,"a17":40}', 
        '[]'::jsonb
    ),
(
        'a31', 
        'Phoenix Wilder', 
        22, 
        'Male', 
        'Indie Darling', 
        120000, 
        58, 
        76, 
        '["Drama","Horror"]', 
        'Available', 
        'Breakout from a critically acclaimed indie horror. Born into Hollywood royalty but rejected it. Estranged from famous parent. Tabloid fodder with actual talent.', 
        'Haunted, beautiful, troubled.', 
        '["Troubled","Talented","Running From Fame"]', 
        '{"a25":30,"a5":-40}', 
        '[]'::jsonb
    ),
(
        'a32', 
        'Sage Morrison', 
        35, 
        'Female', 
        'Indie Darling', 
        155000, 
        67, 
        84, 
        '["Comedy","Drama","Romance"]', 
        'Available', 
        'Improviser and playwright who acts in her own work. Creates ensemble pieces where she''s rarely the lead. More interested in the art than the fame.', 
        'Warm, approachable, creative energy.', 
        '["Collaborative","Creative","Ensemble Player"]', 
        '{"a29":35,"a30":25}', 
        '[]'::jsonb
    ),
(
        'a33', 
        'Jake Holloway', 
        21, 
        'Male', 
        'Newcomer', 
        75000, 
        35, 
        55, 
        '["Action","Comedy"]', 
        'Available', 
        'Star quarterback who got discovered. Zero training, pure natural charisma. Agents are fighting over him. Might be the next big thing or flame out spectacularly.', 
        'All-American, athletic, camera loves him.', 
        '["Raw Talent","Cocky","Untested"]', 
        '{"a9":15}', 
        '[]'::jsonb
    ),
(
        'a34', 
        'Maya Santos', 
        19, 
        'Female', 
        'Newcomer', 
        65000, 
        40, 
        70, 
        '["Drama","Romance"]', 
        'Available', 
        'Won a nationwide talent search. First role ever and she''s already getting Oscar buzz. Either the real deal or the most overhyped newcomer in years.', 
        'Fresh-faced, innocent, surprising depth.', 
        '["Promising","Overwhelmed","Natural"]', 
        '{"a2":10}', 
        '[]'::jsonb
    ),
(
        'a35', 
        'Brandon Liu', 
        24, 
        'Male', 
        'Newcomer', 
        80000, 
        38, 
        62, 
        '["Sci-Fi","Action","Comedy"]', 
        'Available', 
        'Martial arts champion who wants to be an actor. Has the skills but still learning to emote. Working with an acting coach between training sessions.', 
        'Athletic, focused, work in progress.', 
        '["Dedicated","Stiff","Hardworking"]', 
        '{"a3":20}', 
        '[]'::jsonb
    ),
(
        'a36', 
        'Emma Thornton', 
        23, 
        'Female', 
        'Newcomer', 
        70000, 
        42, 
        68, 
        '["Horror","Thriller","Drama"]', 
        'Available', 
        'Theater school valedictorian thrown into Hollywood. Classically trained but adapting to screen. Directors say she''s ''almost there.'' Whatever that means.', 
        'Polished, trained, trying to unlearn technique.', 
        '["Trained","Anxious","Adapting"]', 
        '{"a6":15,"a17":20}', 
        '[]'::jsonb
    ),
(
        'a37', 
        'Diego Reyes', 
        26, 
        'Male', 
        'Newcomer', 
        85000, 
        45, 
        58, 
        '["Romance","Drama","Comedy"]', 
        'Available', 
        'Telenovela star trying to cross over. Huge following in Latin America, unknown in the US. Charming as hell but his English needs work.', 
        'Soap opera handsome, magnetic, accent heavy.', 
        '["Charming","Determined","Fish Out of Water"]', 
        '{"a11":25}', 
        '[]'::jsonb
    ),
(
        'a38', 
        'Lily Park', 
        20, 
        'Female', 
        'Newcomer', 
        60000, 
        32, 
        64, 
        '["Comedy","Romance","Fantasy"]', 
        'Available', 
        'K-pop idol making the jump to Hollywood. Massive international fanbase but acting skeptics abound. More talented than people expect.', 
        'Pop star polished, perfected image.', 
        '["Trained","Disciplined","More Than Expected"]', 
        '{"a20":20}', 
        '[]'::jsonb
    ),
(
        'a39', 
        'Marcus Webb', 
        28, 
        'Male', 
        'Newcomer', 
        90000, 
        44, 
        72, 
        '["Drama","Thriller"]', 
        'Available', 
        'Former marine with a face for drama. Discovered at a VA hospital by a casting director. Brings intense authenticity to military and trauma roles.', 
        'Thousand-yard stare, intimidating presence.', 
        '["Intense","Authentic","Haunted"]', 
        '{"a19":25,"a29":15}', 
        '[]'::jsonb
    ),
(
        'a40', 
        'Chloe Anderson', 
        22, 
        'Female', 
        'Newcomer', 
        55000, 
        30, 
        60, 
        '["Comedy","Romance"]', 
        'Available', 
        'TikTok star with 10 million followers. Studios think she''s the key to Gen Z. Critics think she''s a gimmick. Truth is probably somewhere in between.', 
        'Internet-ready, constant content creator.', 
        '["Social Media Native","Self-Aware","Hustler"]', 
        '{"a20":30}', 
        '[]'::jsonb
    );


-- 6. Reset Scripts (Delete All)
DELETE FROM scripts;

-- 7. Insert Seed Scripts
INSERT INTO scripts (
    id, title, genre, quality, complexity, base_cost, 
    description, tagline, required_cast, tone, created_at
) VALUES
(
        '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d', 
        'Memory Lane', 
        'Romance', 
        92, 
        85, 
        800000, 
        'Two strangers meet at a memory clinic where people can selectively erase painful experiences. As they fall in love, they must decide if forgetting the past is worth losing their future.', 
        'Some memories are worth keeping.', 
        2, 
        'Melancholic', 
        NOW()
    ),
(
        '109156be-c4fb-41ea-b1b4-efe1671c5836', 
        'The Double Cross', 
        'Thriller', 
        95, 
        90, 
        1200000, 
        'A detective infiltrates a crime syndicate while unknowingly hunting another undercover agent. When their identities collide, loyalty becomes a deadly game.', 
        'Trust no one. Suspect everyone.', 
        3, 
        'Serious', 
        NOW()
    ),
(
        '6ec0bd7f-11c0-43da-975e-2a8ad9ebae0b', 
        'Road to Starlight', 
        'Comedy', 
        88, 
        65, 
        450000, 
        'A dysfunctional family embarks on a chaotic cross-country road trip to support their youngest member''s dream of competing in a national talent show.', 
        'Every family has its bumps.', 
        2, 
        'Lighthearted', 
        NOW()
    ),
(
        'c56a4180-65aa-42ec-a945-5fd21dec0538', 
        'Desert Fortune', 
        'Thriller', 
        96, 
        88, 
        950000, 
        'A welder stumbles upon a briefcase full of cash in the desert, triggering a cat-and-mouse chase with a relentless hitman who never stops hunting.', 
        'Some money costs more than it''s worth.', 
        2, 
        'Serious', 
        NOW()
    ),
(
        '0f47d446-44b4-4340-97F1-3b5674c2e6f4', 
        'Last Night Out', 
        'Comedy', 
        82, 
        55, 
        350000, 
        'Two best friends attempt one final epic party before graduating high school, but everything that can go wrong does.', 
        'One night. Zero limits.', 
        2, 
        'Lighthearted', 
        NOW()
    ),
(
        '4e95ce32-756e-4433-87f5-34351b858485', 
        'Black Gold', 
        'Drama', 
        98, 
        92, 
        1500000, 
        'An oil prospector''s ruthless ambition destroys everyone around him as he builds an empire in the California desert at the turn of the century.', 
        'Greed has no limits.', 
        2, 
        'Serious', 
        NOW()
    ),
(
        'd8c1e847-1934-4b52-b8ec-f2c9747124f1', 
        'Nine Months Later', 
        'Comedy', 
        85, 
        60, 
        400000, 
        'A quirky teenager navigates an unexpected pregnancy with humor and heart, finding family in the most unlikely places.', 
        'Growing up happens faster than you think.', 
        2, 
        'Lighthearted', 
        NOW()
    ),
(
        'a5027581-995f-4161-a8cc-0a149d873c3d', 
        'The Illusionists', 
        'Thriller', 
        90, 
        87, 
        750000, 
        'Two rival magicians in Victorian London become obsessed with creating the perfect trick, sacrificing everything in their dangerous competition.', 
        'Every great magic trick has a price.', 
        2, 
        'Serious', 
        NOW()
    ),
(
        '3e4666bf-d515-46cc-b70c-c6b7582b5358', 
        'The Faun''s Maze', 
        'Fantasy', 
        94, 
        85, 
        900000, 
        'A young girl escapes into a dark fairy tale world to cope with the horrors of war-torn Spain, where mythical creatures offer both danger and salvation.', 
        'Where nightmares and fairy tales meet.', 
        2, 
        'Dark', 
        NOW()
    ),
(
        '71329c29-8732-4d51-9f79-c54d7f57c503', 
        'Million Dollar Question', 
        'Drama', 
        91, 
        78, 
        650000, 
        'A street kid from Mumbai becomes a game show sensation, but his incredible winning streak leads to accusations of cheating and a journey through his extraordinary past.', 
        'Every answer tells a story.', 
        2, 
        'Uplifting', 
        NOW()
    ),
(
        '96b65392-4148-4395-9d33-9118c772e0d3', 
        'The Ghost Protocol', 
        'Action', 
        87, 
        75, 
        600000, 
        'An amnesiac operative washes ashore with no memory but deadly skills. As assassins close in, he must piece together his identity before it''s too late.', 
        'He doesn''t know who he is. They know who he was.', 
        2, 
        'Serious', 
        NOW()
    ),
(
        'b4507119-21b9-4a0b-8d65-4dffc3619582', 
        'Unexpected Delivery', 
        'Romance', 
        78, 
        50, 
        300000, 
        'A one-night stand turns into a nine-month commitment when two polar opposites must figure out if they can build a relationship while building a family.', 
        'Life''s biggest surprise.', 
        2, 
        'Lighthearted', 
        NOW()
    );

COMMIT;